### ISSUE TITLE
Development timeline

### ISSUE THREAD

**Issue by cylammarco** [TOMToolkit/tom_lt#7]
Is there a development timeline for these [new features](https://github.com/TOMToolkit/tom_lt#future-extentions-to-the-module-will-enable-in-order-of-planned-implementation)?

**Comment by blancmatter** [comment]
Hi Marco,

I've got prototype code for this and although no 'firm' timeline. After some minimal testing,  it will ready to be incorporated into the module. Certainly this month, hope this helps
